### ISSUE TITLE
Symfony support

### ISSUE THREAD

**Issue by veewee** [pheature-flags/datetime-interval-segment-types#13]
Hello,

Thanks for the package.
I am trying to install it in a Symfony project, but it doesn't seem to accept the strategy:

Config:

```yaml
services:
  Pheature\Model\DateTime\IntervalSegmentFactory:
    arguments:
      - '@StellaMaris\Clock\ClockInterface'

pheature_flags:
  segment_types:
    - { type: 'datetime_matching_segment', factory_id: 'Pheature\Model\DateTime\IntervalSegmentFactory' }
```

The problem here, is that `vendor/pheature/symfony-toggle/src/DependencyInjection/SegmentFactoryPass.php` registers the factory_id as class instead of reference to existing service. This makes configuring dependencies for the factory not possible in the symfony-toggle package.

Suggested improvements:

* Maybe it makes more sense to register an alias to the factory_id (if it already exists in the container) instead?
* Maybe `StellaMaris` can be replaced by the accepted clock PSR?
* Maybe activating this plugin in Symfony could be documented a bit better? Alternatively a flex recipe can be added to set up the segment type for the end-user?

**Comment by kpicaza** [comment]
Hello @veewee :wave: ,

Thanks for your feedback. Actually, there is no Symfony integration for the date-time interval segment package. We use it by enabling the new segment types in the project config. You can find an example here: https://github.com/kpicaza/pheature-symfony-pre-example/blob/main/config/packages/pheature_flags.yaml

Testing your issue, I found another issue merging configs in the Symfony bundle. This issue forces us to set up complete segment_types configuration options instead of adding only the custom segments config. 

```yaml
pheature_flags:
  ...
  segment_types:
    # Bundle segment types 
    - { type: 'identity_segment', factory_id: 'Pheature\Model\Toggle\SegmentFactory' }
    - { type: 'strict_matching_segment', factory_id: 'Pheature\Model\Toggle\SegmentFactory' }
    - { type: 'in_collection_matching_segment', factory_id: 'Pheature\Model\Toggle\SegmentFactory' }
    # Custom segment types
    - { type: 'datetime_matching_segment', factory_id: 'Pheature\Model\DateTime\IntervalSegmentFactory' }
    - { type: 'datetime_strict_matching_segment', factory_id: 'Pheature\Model\DateTime\IntervalSegmentFactory' }

services:
  StellaMaris\Clock\ClockInterface:
    class: Beste\Clock\SystemClock
    factory: [Beste\Clock\SystemClock, 'create']

  datetime_matching_segment:
    class: Pheature\Model\DateTime\IntervalSegmentFactory
    arguments:
      - '@StellaMaris\Clock\ClockInterface'

  datetime_strict_matching_segment:
    class: Pheature\Model\DateTime\IntervalSegmentFactory
    arguments:
      - '@StellaMaris\Clock\ClockInterface'
```

> Maybe StellaMaris can be replaced by the accepted clock PSR?

100% The PSR Clock is accepted, and there is no reason to use Stalamaris/clock anymore. I'll open an issue to do it.

> Maybe activating this plugin in Symfony could be documented a bit better? Alternatively a flex recipe can be added to set up the segment type for the end-user?

Sure, We apologize for the inconvenience. You are right. There is no detailed bundle documentation. We have a working example at https://github.com/kpicaza/pheature-symfony-pre-example. 

About a flex recipe, it sounds nice. The Symfony bundle don't use recipes because it loads all services using the compiler passes and default config. But enabling datetime-interval-segment-types requires at least registering three services and two segment types. The Symfony recipe will allow end users using it out of the box.
